version: "2.0"

services: 
    app:
        image: app:${tag}
        restart: always
        ports:
            - "80:7001"
        volumes:
            - "../volumes/logs:/app/logs"
            - ./config:/app/config
        links:
            - redis
            - mysql
        depends_on:
            - redis
            - mysql
    redis: 
        image: redis:3.2
        restart: always
        ports:
            - "6379:6379"
    mysql:
        image: mysql:latest
        restart: always
        ports:
            - "3306:3306"
        environment:
            - MYSQL_DATABASE=egg
            - MYSQL_ROOT_PASSWORD=123456
        volumes:
            - "/data/mysql/db:/var/lib/mysql"
            - "/data/mysql/conf:/etc/mysql/conf.d"